### ISSUE TITLE
Invlaid form body 

### ISSUE THREAD

**Issue by Hosfad** [Sheweny/discord-backup#2]

**Comment by Hosfad** [comment]
Hey there , im trying yo use your package , and backing up a server , works great , Im having an issue loading a backup to a server though :O , it gives  me the following error : 
```
iscordAPIError[50035]: Invalid Form Body
name[BASE_TYPE_REQUIRED]: This field is required
    at SequentialHandler.runRequest (/home/hosfad/Desktop/discord-backup-api/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:287:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at SequentialHandler.queueRequest (/home/hosfad/Desktop/discord-backup-api/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:99:14)
    at REST.request (/home/hosfad/Desktop/discord-backup-api/node_modules/@discordjs/rest/src/lib/REST.ts:50:22)
    at GuildChannelManager.create (/home/hosfad/Desktop/discord-backup-api/node_modules/discord.js/src/managers/GuildChannelManager.js:145:18)
    at loadChannels (/home/hosfad/Desktop/discord-backup-api/node_modules/@sheweny/backup/dist/functions/load.js:80:9)
    at load (/home/hosfad/Desktop/discord-backup-api/node_modules/@sheweny/backup/dist/functions/load.js:13:5)
    at Client.<anonymous> (/home/hosfad/Desktop/discord-backup-api/src/index.ts:24:3)
[ERROR] 11:28:37 DiscordAPIError[50035]: Invalid Form Body
name[BASE_TYPE_REQUIRED]: This field is required
``` 

Any ideas please ?

**Comment by Smaug6739** [comment]
Hello, what is the version of discord.js used ?

**Comment by Hosfad** [comment]
Hello discord js v-14.2.0

**Comment by Smaug6739** [comment]
for the moment the package is on discord.js 13 but an update should arrive soon, I will see the progress and I will try to make an update during the day

**Comment by Hosfad** [comment]
Awesome thank you , it said version 13 or newer so i assumed it would work for 14.2.0 .
I will keep an eye out for a pull request :) thanks again
